// src/renderer/components/Controls/Controls.jsx
import React from 'react';
import PropTypes from 'prop-types';
import playSvg from 'open-iconic/svg/media-play.svg';
import pauseSvg from 'open-iconic/svg/media-pause.svg';
import prevSvg from 'open-iconic/svg/media-step-backward.svg';
import nextSvg from 'open-iconic/svg/media-step-forward.svg';
import styles from './Controls.css';

export default function Controls({
  isPlaying,
  togglePlay,
  skipPrev,
  skipNext
}) {
  return (
    <div className={styles.controls}>
      <span
        className={styles.prevIcon}
        dangerouslySetInnerHTML={{ __html: prevSvg }}
        onClick={skipPrev}
      />
      <span
        className={`${styles.circleIcon} ${
          isPlaying ? styles.pauseIcon : styles.playIcon
        }`}
        dangerouslySetInnerHTML={{ __html: isPlaying ? pauseSvg : playSvg }}
        onClick={togglePlay}
      />
      <span
        className={styles.nextIcon}
        dangerouslySetInnerHTML={{ __html: nextSvg }}
        onClick={skipNext}
      />
    </div>
  );
}

Controls.propTypes = {
  isPlaying: PropTypes.bool,
  togglePlay: PropTypes.func,
  skipPrev: PropTypes.func,
  skipNext: PropTypes.func
};

// src/renderer/components/player/Controls.vue
<template>
  <div class="buttons">
    <span @click="triggerPrev" v-once v-html="prevSvg" class="icon"></span>
    <span @click="triggerTogglePlay" v-if="isPlaying" v-once v-html="pauseSvg" class="icon"></span>
    <span @click="triggerTogglePlay" v-else v-once v-html="playSvg" class="icon"></span>
    <span @click="triggerNext" v-once v-html="nextSvg" class="icon"></span>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';
import playSvg from "open-iconic/svg/media-play.svg";
import pauseSvg from "open-iconic/svg/media-pause.svg";
import prevSvg from "open-iconic/svg/media-step-backward.svg";
import nextSvg from "open-iconic/svg/media-step-forward.svg";

@Component({
  props: {
    isPlaying: Boolean
  }
})
export default class Controls extends Vue {
  isPlaying: boolean;

  get playSvg(): string {
    return playSvg;
  }

  get pauseSvg(): string {
    return pauseSvg;
  }

  get prevSvg(): string {
    return prevSvg;
  }

  get nextSvg(): string {
    return nextSvg;
  }

  triggerPrev(): void {
    this.$store.dispatch("prev");
  }

  triggerTogglePlay(): void {
    this.$store.dispatch("togglePlay");
  }

  triggerNext(): void {
    this.$store.dispatch("next");
  }
}
</script>

<style scoped>
.icon {
  fill: #a0a0a0;
}
</style>
